import { Container } from '@mui/material'
import Head from 'next/head'
import React from 'react'
import axios from 'axios'
import { GetServerSideProps, GetStaticPaths, GetStaticProps } from 'next'

interface IVehicleFipeInfo {
  TipoVeiculo: number
  Valor: string
  Marca: string
  Modelo: string
  AnoModelo: number
  Combustivel: string
  CodigoFipe: string
  MesReferencia: string
  SiglaCombustivel: string
}

export default function Result(vehicleFipeInfo: IVehicleFipeInfo) {
  console.log(vehicleFipeInfo)
  return (
    <>
      <Head>
        <title>Front-End Test - Tabela Fipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          component="main"
          maxWidth="lg"
          sx={{
            height: '100vh',
            width: '100vw',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <div>
            <h1>
              Tabela Fipe: Preço {vehicleFipeInfo.Marca}{' '}
              {vehicleFipeInfo.Modelo} {vehicleFipeInfo.AnoModelo}
            </h1>
            <p>{vehicleFipeInfo.Valor}</p>
            <span>Este é o preço de compra do veículo</span>
          </div>
        </Container>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<
  any,
  { slug: string; modelo: string; marca: string; ano: string }
> = async ({ query }) => {
  const marca = String(query.marca)
  const modelo = String(query.modelo)
  const ano = String(query.ano)

  // const response = await axios.get(
  //   `https://parallelum.com.br/fipe/api/v1/carros/marcas/${marca}/modelos/${modelo}/anos/${ano}`
  // )

  // const vehicleFipeInfo = response.data
  try {
    const { data } = await axios.get(
      `https://parallelum.com.br/fipe/api/v1/carros/marcas/${marca}/modelos/${modelo}/anos/${ano}`
    )

    if (!data) {
      return { notFound: true }
    }

    return { props: { ...data } }
  } catch (error) {
    return { notFound: true }
  }
}
