import {
  Autocomplete,
  Box,
  Button,
  Container,
  Paper,
  TextField,
} from '@mui/material'
import axios from 'axios'
import { GetStaticProps } from 'next'
import Head from 'next/head'

interface CarProps {
  codigo: string
  nome: string
}
interface HomeProps {
  cars: CarProps[]
}

export default function Home({ cars }: HomeProps) {
  const options = [
    { label: 'The Godfather', id: 1 },
    { label: 'Pulp Fiction', id: 2 },
  ]

  const carBrands = [...cars]

  console.log(cars)

  return (
    <>
      <Head>
        <title>Front-End Test - Tabela Fipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          component="main"
          maxWidth="lg"
          sx={{
            height: '100vh',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            background: '#f1f1f1',
          }}
        >
          <Paper sx={{ my: { xs: 3, md: 6 }, p: '2rem 3rem' }}>
            <h1>Tabela Fipe</h1>
            <p>Consulte o valor de um veículo de forma gratuita</p>
            <Autocomplete
              disablePortal
              id="marca"
              options={carBrands}
              sx={{ width: 300, my: '0.5rem' }}
              renderInput={(params) => (
                <TextField {...params} label="Marca" variant="filled" />
              )}
            />
            <Autocomplete
              disablePortal
              id="modelo"
              options={options}
              sx={{ width: 300 }}
              renderInput={(params) => (
                <TextField {...params} label="Modelo" variant="filled" />
              )}
            />

            <Autocomplete
              disablePortal
              id="ano"
              options={options}
              sx={{ width: 300 }}
              renderInput={(params) => (
                <TextField {...params} label="Ano" variant="filled" />
              )}
            />
            <Button variant="contained">Consultar Preço</Button>
          </Paper>
        </Container>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const carBrands = await axios.get(
    'https://parallelum.com.br/fipe/api/v1/carros/marcas'
  )

  const cars = carBrands.data.map((car: CarProps) => {
    return {
      label: car.nome,
      id: car.codigo,
    }
  })

  return {
    props: {
      cars,
    },
    revalidate: 60 * 60 * 2, // 2 hours,
  }
}
